name: csvplus
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pandas=2.3.3
  - numpy=2.4.1
  - scipy=1.17.0
  - rapidfuzz=3.14.3

  # Docs / Quarto execution
  - jupyter
  - ipykernel
  - nbformat

  # Testing
  - pytest=9.0.2
  - pytest-cov=7.0.0

  # Documentation
  - quartodoc=0.11.1

  # Tooling
  - pip=25.3
  - pip:
      - faker
      - flake8
